
/* BridgeKit Maritime Operations expansion */
const PRO_KEYS={role:"bridgekit_role",favorites:"bridgekit_favorites",equipment:"bridgekit_equipment",ir:"bridgekit_irlog",shore:"bridgekit_shorecheck",rob:"bridgekit_rob"};
state.pro={ais:[],aisFetchedAt:null,forecast:[],forecastFetchedAt:null,warnings:[],warningsFetchedAt:null,aisMap:null,aisLayers:[],aisRouteLayer:null,aisVectorLayers:[],aisCpaLayer:null,intelMap:null,intelLayers:[],role:localStorage.getItem(PRO_KEYS.role)||"general"};

const PRO_TOOLS={
 passage:{name:"Passage Planner",page:"passage",icon:"route",desc:"Route · ETA · GPX · RTZ"},intelligence:{name:"Route Intelligence",page:"intelligence",icon:"radar",desc:"AIS · weather · warnings"},ais:{name:"AIS Traffic",page:"ais",icon:"ship",desc:"Live traffic · CPA screening"},weather:{name:"Weather Along Route",page:"weather",icon:"weather",desc:"Wave · wind · current"},cpa:{name:"CPA / TCPA",page:"cpa",icon:"radar",desc:"Relative-motion check"},ukc:{name:"UKC",page:"ukc",icon:"depth",desc:"Under-keel clearance"},warnings:{name:"Warnings",page:"warnings",icon:"warning",desc:"Coastal · NAVAREA XIX"},fuel:{name:"Fuel & ROB",page:"fuel",icon:"fuel",desc:"Endurance · changeover · transfer"},engineering:{name:"Engineering",page:"engineering",icon:"engine",desc:"Generators · SFOC · pumps"},electrical:{name:"Electrical",page:"electrical",icon:"bolt",desc:"3-phase · battery · IR log"},bunkering:{name:"Bunkering & ORB",page:"bunkering",icon:"fuel",desc:"Distribution · BDN · records"},watch:{name:"Watch Tools",page:"watch",icon:"watch",desc:"Snapshot · handover"},vessel:{name:"Vessel Profiles",page:"vessel",icon:"vessel",desc:"Particulars · tanks · power"},limits:{name:"Operational Limits",page:"limits",icon:"warning",desc:"Planning thresholds"},equipment:{name:"Equipment",page:"equipment",icon:"equipment",desc:"Local equipment cards"},reports:{name:"Reports",page:"reports",icon:"report",desc:"Passage · operations · export"},quick:{name:"Quick Tools",page:"quick",icon:"compass",desc:"Daily calculations"}
};
const ROLE_DEFAULTS={general:["passage","intelligence","fuel","engineering","bunkering","watch"],navigator:["passage","intelligence","ais","weather","cpa","ukc"],engineer:["fuel","engineering","bunkering","equipment","watch","reports"],electrician:["electrical","engineering","equipment","watch","reports","fuel"]};
function iconUse(id,cls=""){return `<svg class="${cls}"><use href="assets/icons.svg#${id}"/></svg>`}
function proEsc(s){return esc(s)}
function nowIso(){return new Date().toISOString()}
function ageSec(iso){const d=new Date(iso);return isNaN(d)?Infinity:Math.max(0,(Date.now()-d.getTime())/1000)}
function ageLabel(iso){const s=ageSec(iso);if(!Number.isFinite(s))return"Not loaded";if(s<60)return`${Math.round(s)} sec ago`;if(s<3600)return`${Math.round(s/60)} min ago`;return`${(s/3600).toFixed(1)} h ago`}
function staleClass(iso){const lim=(state.vessel.staleMinutes||10)*60,s=ageSec(iso);return s>lim?"caution":"normal"}
function setHealth(id,status,text){const el=$(id);if(!el)return;el.className=`health-chip ${status}`;el.querySelector("b").textContent=text}
function updateUtc(){const d=new Date();const t=d.toISOString().slice(11,19);if($("utcClock"))$("utcClock").textContent=t;if($("watchUtc"))$("watchUtc").textContent=`${t} UTC`}
setInterval(updateUtc,1000);updateUtc();

// Role workspace + favorites
function favorites(){try{return JSON.parse(localStorage.getItem(PRO_KEYS.favorites)||"null")||ROLE_DEFAULTS[state.pro.role]||ROLE_DEFAULTS.general}catch{return ROLE_DEFAULTS[state.pro.role]}}
function saveFavorites(arr){localStorage.setItem(PRO_KEYS.favorites,JSON.stringify([...new Set(arr)].slice(0,8)));renderPinned();renderFavoriteSettings()}
function renderPinned(){const arr=favorites();const box=$("pinnedTools");if(!box)return;box.innerHTML=arr.filter(k=>PRO_TOOLS[k]).map(k=>{const t=PRO_TOOLS[k];return `<div class="pinned-tool" data-open-tool="${k}"><span>${iconUse(t.icon)}</span><span><strong>${t.name}</strong><small>${t.desc}</small></span><button class="pin-star active" data-unpin="${k}" title="Unpin">★</button></div>`}).join("")||'<div class="source-status">No pinned tools.</div>';box.querySelectorAll("[data-open-tool]").forEach(el=>el.addEventListener("click",e=>{if(e.target.closest("[data-unpin]"))return;showPage(PRO_TOOLS[el.dataset.openTool].page)}));box.querySelectorAll("[data-unpin]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();saveFavorites(arr.filter(x=>x!==b.dataset.unpin))}));}
function renderFavoriteSettings(){const box=$("favoriteSettings");if(!box)return;const f=favorites();box.innerHTML=Object.entries(PRO_TOOLS).map(([k,t])=>`<label class="fav-setting"><input type="checkbox" data-fav-setting="${k}" ${f.includes(k)?"checked":""}>${t.name}</label>`).join("");box.querySelectorAll("[data-fav-setting]").forEach(c=>c.addEventListener("change",()=>{let a=favorites();a=c.checked?[...a,c.dataset.favSetting]:a.filter(x=>x!==c.dataset.favSetting);saveFavorites(a)}));}
function applyRole(role){state.pro.role=role;localStorage.setItem(PRO_KEYS.role,role);if($("roleSelect"))$("roleSelect").value=role;if($("settingsRole"))$("settingsRole").value=role;document.documentElement.dataset.role=role;if($("roleWorkspaceLabel"))$("roleWorkspaceLabel").textContent=`${role[0].toUpperCase()+role.slice(1)} workspace · live and local context`;if(!localStorage.getItem(PRO_KEYS.favorites))renderPinned();}
$("roleSelect")?.addEventListener("change",e=>{localStorage.removeItem(PRO_KEYS.favorites);applyRole(e.target.value);renderPinned();renderFavoriteSettings()});
$("settingsRole")?.addEventListener("change",e=>{$("roleSelect").value=e.target.value;localStorage.removeItem(PRO_KEYS.favorites);applyRole(e.target.value);renderPinned();renderFavoriteSettings()});

// Enhanced command palette
const OLD_SEARCH=SEARCH_ITEMS;
Object.assign(NAV_NO,{ais:"AIS-trafikk",weather:"Vær langs rute",fuel:"Drivstoff & ROB",electrical:"Elektro",watch:"Vaktverktøy",limits:"Operasjonelle grenser",equipment:"Utstyr",reports:"Rapporter"});
function proSearch(){const q=$("globalSearch").value.trim().toLowerCase(),box=$("searchDrop");if(!q)return;const tools=Object.entries(PRO_TOOLS).filter(([k,t])=>(t.name+" "+t.desc).toLowerCase().includes(q)).map(([k,t])=>({type:"Tool",name:t.name,id:t.page}));const voyages=state.voyages.filter(v=>v.name?.toLowerCase().includes(q)).map(v=>({type:"Voyage",name:v.name,id:"voyages",voyage:v.id}));const eq=loadEquipment().filter(v=>(v.name+" "+v.type).toLowerCase().includes(q)).map(v=>({type:"Equipment",name:v.name,id:"equipment"}));const all=[...tools,...voyages,...eq].slice(0,9);box.innerHTML=all.length?all.map(x=>`<button data-pro-search="${x.id}"><span>${proEsc(x.name)}</span><small>${x.type}</small></button>`).join(""):'<div class="source-status">No matching tools or records.</div>';box.hidden=false;box.querySelectorAll("[data-pro-search]").forEach(b=>b.addEventListener("click",()=>{showPage(b.dataset.proSearch);$("globalSearch").value="";box.hidden=true}));}
$("globalSearch")?.addEventListener("input",()=>setTimeout(proSearch,0));

// System health
async function refreshSystemHealth(){let auth=null;try{auth=await api("/api/auth/status");setHealth("healthAis",auth.ais?.authenticated?"normal":"alert",auth.ais?.authenticated?"LIVE":"AUTH");setHealth("healthBw",auth.api?.authenticated?"normal":"alert",auth.api?.authenticated?"LIVE":"AUTH")}catch{setHealth("healthAis","unavailable","OFF");setHealth("healthBw","unavailable","OFF")};return auth}

function activeRoute(){const v=state.voyages[0];return state.routes.find(r=>r.id===v?.routeId)||state.route}
function routeBounds(route=activeRoute(),padNm=5){if(!route?.waypoints?.length)return null;const lats=route.waypoints.map(p=>+p.lat),lons=route.waypoints.map(p=>+p.lon),pad=padNm/60;return{minLat:Math.min(...lats)-pad,maxLat:Math.max(...lats)+pad,minLon:Math.min(...lons)-pad,maxLon:Math.max(...lons)+pad}}
function destPoint(lat,lon,brg,distNm){const d=distNm/EARTH_NM,b=toRad(brg),p1=toRad(lat),l1=toRad(lon),p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b)),l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return{lat:toDeg(p2),lon:((toDeg(l2)+540)%360)-180}}
function vesselTypeGroup(t){const n=+(t.shipType??t.type??-1);if(n===30)return"fishing";if(n===51)return"sar";if(n===52)return"tug";if(n>=60&&n<=69)return"passenger";if(n>=70&&n<=79)return"cargo";if(n>=80&&n<=89)return"tanker";return"other"}
function targetTime(t){return t.msgtime||t.messageTime||t.timestamp||null}
function targetStatus(t){const age=ageSec(targetTime(t)),c=cpaForTarget(t,activeRoute());if(age>(state.vessel.staleMinutes||10)*60)return"stale";if(c&&c.tcpaHours>=0&&c.cpa<=(state.vessel.cpa||1))return"alert";if(c&&c.tcpaHours>=0&&c.cpa<=(state.vessel.cpa||1)*2)return"caution";return"normal"}

// AIS map
function initAisMap(){if(state.pro.aisMap||!window.L||!$("aisMap"))return;state.pro.aisMap=L.map("aisMap").setView([59.15,10.35],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(state.pro.aisMap);L.tileLayer("https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png",{maxZoom:18,attribution:"OpenSeaMap"}).addTo(state.pro.aisMap);}
function clearAisLayers(){state.pro.aisLayers.forEach(x=>x.remove());state.pro.aisLayers=[];state.pro.aisVectorLayers.forEach(x=>x.remove());state.pro.aisVectorLayers=[];if(state.pro.aisRouteLayer){state.pro.aisRouteLayer.remove();state.pro.aisRouteLayer=null}if(state.pro.aisCpaLayer){state.pro.aisCpaLayer.remove();state.pro.aisCpaLayer=null}}
function filteredAis(){const type=$("aisTypeFilter")?.value||"all",min=+$("aisMinSog")?.value||0,hide=$("aisHideStationary")?.checked,corr=$("aisCorridorOnly")?.checked,route=activeRoute(),corridor=state.vessel.corridor||5;return state.pro.ais.filter(t=>{const sog=+(t.speedOverGround??t.sog??0);if(type!=="all"&&vesselTypeGroup(t)!==type)return false;if(sog<min)return false;if(hide&&sog<.5)return false;if(corr&&route?.waypoints?.length>1){const d=routePointDistance({lat:+(t.latitude??t.lat),lon:+(t.longitude??t.lon)},route.waypoints);if(d>corridor)return false}return true})}
function showTargetPanel(t){const c=cpaForTarget(t,activeRoute()),age=ageLabel(targetTime(t));$("aisSelected").className="target-panel";$("aisSelected").innerHTML=`<h3>${proEsc(t.name||"Unknown vessel")}</h3><div class="target-grid"><div><small>MMSI</small><strong>${proEsc(String(t.mmsi||"—"))}</strong></div><div><small>TYPE</small><strong>${vesselTypeGroup(t)}</strong></div><div><small>SOG</small><strong>${fmt(+(t.speedOverGround??0),1)} kn</strong></div><div><small>COG</small><strong>${fmt(+(t.courseOverGround??0),0)}°</strong></div><div><small>HEADING</small><strong>${Number.isFinite(+t.trueHeading)?fmt(+t.trueHeading,0)+"°":"—"}</strong></div><div><small>DATA AGE</small><strong>${age}</strong></div><div><small>CPA</small><strong>${c?fmt(c.cpa,2)+" NM":"—"}</strong></div><div><small>TCPA</small><strong>${c&&Number.isFinite(c.tcpaHours)?fmt(c.tcpaHours*60,0)+" min":"—"}</strong></div></div>`;drawCpaVisualization(t,c)}
function drawCpaVisualization(t,c){if(!state.pro.aisMap)return;if(state.pro.aisCpaLayer)state.pro.aisCpaLayer.remove();if(!c||!Number.isFinite(c.tcpaHours)||c.tcpaHours<0||c.tcpaHours>2)return;const r=activeRoute();if(!(r?.waypoints?.length>1))return;const own=r.waypoints[0],ownCog=bearing(own,r.waypoints[1]),ownSog=+(own.speed||r.speed||0),tar={lat:+(t.latitude??t.lat),lon:+(t.longitude??t.lon)},tarCog=+(t.courseOverGround??0),tarSog=+(t.speedOverGround??0),op=destPoint(own.lat,own.lon,ownCog,ownSog*c.tcpaHours),tp=destPoint(tar.lat,tar.lon,tarCog,tarSog*c.tcpaHours);state.pro.aisCpaLayer=L.layerGroup([L.polyline([[own.lat,own.lon],[op.lat,op.lon]],{color:"#2089c7",dashArray:"5 5"}),L.polyline([[tar.lat,tar.lon],[tp.lat,tp.lon]],{color:"#d57624",dashArray:"5 5"}),L.polyline([[op.lat,op.lon],[tp.lat,tp.lon]],{color:c.cpa<=(state.vessel.cpa||1)?"#cf4f56":"#c8952b",weight:3})]).addTo(state.pro.aisMap)}
function renderAisMap(fit=false){initAisMap();if(!state.pro.aisMap)return;clearAisLayers();const r=activeRoute();if($("aisShowRoute")?.checked&&r?.waypoints?.length>1){state.pro.aisRouteLayer=L.polyline(r.waypoints.map(p=>[p.lat,p.lon]),{color:"#1688cc",weight:4}).addTo(state.pro.aisMap);if(fit)state.pro.aisMap.fitBounds(state.pro.aisRouteLayer.getBounds(),{padding:[30,30]})}const vectorMin=+$("aisVectorMin")?.value||10;for(const t of filteredAis()){const lat=+(t.latitude??t.lat),lon=+(t.longitude??t.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const sog=+(t.speedOverGround??0),cog=+(t.courseOverGround??0),status=targetStatus(t);const icon=L.divIcon({className:"ais-marker-wrap",html:`<div class="ais-symbol ${status}" style="transform:rotate(${Number.isFinite(cog)?cog:0}deg)"></div>`,iconSize:[18,22],iconAnchor:[9,11]});const m=L.marker([lat,lon],{icon}).addTo(state.pro.aisMap);m.on("click",()=>showTargetPanel(t));m.bindTooltip(`${proEsc(t.name||"Unknown")} · ${fmt(sog,1)} kn`);state.pro.aisLayers.push(m);if($("aisShowVectors")?.checked&&sog>.2){const d=destPoint(lat,lon,cog,sog*vectorMin/60),v=L.polyline([[lat,lon],[d.lat,d.lon]],{color:status==="alert"?"#cf4f56":status==="caution"?"#c8952b":"#2e9b6f",weight:1.5,opacity:.75}).addTo(state.pro.aisMap);state.pro.aisVectorLayers.push(v)}}$("aisTargetCount").textContent=state.pro.ais.length;const corridor=r?.waypoints?.length>1?state.pro.ais.filter(t=>routePointDistance({lat:+(t.latitude??t.lat),lon:+(t.longitude??t.lon)},r.waypoints)<=(state.vessel.corridor||5)).length:"—";$("aisCorridorCount").textContent=corridor;$("opsAisCount").textContent=corridor==="—"?`${state.pro.ais.length} targets`:`${corridor} in corridor`;$("opsAisAge").textContent=ageLabel(state.pro.aisFetchedAt);}
async function loadAisTraffic(fit=false){initAisMap();const r=activeRoute(),b=routeBounds(r,state.vessel.corridor||5);let qs;if(b)qs=new URLSearchParams(b);else if(state.pro.aisMap){const bb=state.pro.aisMap.getBounds();qs=new URLSearchParams({minLat:bb.getSouth(),maxLat:bb.getNorth(),minLon:bb.getWest(),maxLon:bb.getEast()})}try{$("aisLiveChip").className="status-chip info";$("aisLiveChip").textContent="LOADING";const data=await api("/api/ais/latest?"+qs.toString());state.pro.ais=Array.isArray(data)?data:(data.items||data.data||[]);state.pro.aisFetchedAt=nowIso();$("aisFetchedAt").textContent=new Date().toISOString().slice(11,19)+" UTC";$("aisLiveChip").className="status-chip normal";$("aisLiveChip").textContent="LIVE";setHealth("healthAis","normal","LIVE");renderAisMap(fit);updateDataAge()}catch(e){$("aisLiveChip").className="status-chip alert";$("aisLiveChip").textContent="ERROR";setHealth("healthAis","alert","ERR");$("aisSelected").className="target-panel empty";$("aisSelected").textContent=`AIS request failed: ${e.message}`}}
$("refreshAis")?.addEventListener("click",()=>loadAisTraffic(false));$("fitAisRoute")?.addEventListener("click",()=>renderAisMap(true));["aisTypeFilter","aisMinSog","aisHideStationary","aisCorridorOnly","aisShowRoute","aisShowVectors","aisVectorMin"].forEach(id=>$(id)?.addEventListener("change",()=>renderAisMap(false)));

// Weather
function sampleName(s,i){return s.name||s.pointName||`P${i+1}`}
function wxStatus(s){const hs=+s.hs,w=+s.windKn,c=+s.currentKn;if(Number.isFinite(hs)&&state.vessel.maxHs&&hs>state.vessel.maxHs)return"alert";if(Number.isFinite(w)&&state.vessel.maxWind&&w>state.vessel.maxWind)return"alert";if(Number.isFinite(c)&&state.vessel.maxCurrent&&c>state.vessel.maxCurrent)return"alert";return"normal"}
function wxValue(v,unit){return Number.isFinite(+v)?`${fmt(+v,1)} ${unit}`:"—"}
function renderWeather(){const arr=state.pro.forecast||[];const valid=arr.filter(s=>Number.isFinite(+s.hs)||Number.isFinite(+s.windKn)||Number.isFinite(+s.currentKn));const hs=valid.map(s=>+s.hs).filter(Number.isFinite),wi=valid.map(s=>+s.windKn).filter(Number.isFinite),cu=valid.map(s=>+s.currentKn).filter(Number.isFinite);$("wxMaxHs").textContent=hs.length?`${fmt(Math.max(...hs),1)} m`:"—";$("wxMaxWind").textContent=wi.length?`${fmt(Math.max(...wi),1)} kn`:"—";$("wxMaxCurrent").textContent=cu.length?`${fmt(Math.max(...cu),1)} kn`:"—";const alerts=valid.filter(x=>wxStatus(x)==="alert").length;$("wxLimitStatus").textContent=valid.length?(alerts?`${alerts} exceedance(s)`:"Within entered limits"):"No numeric values";$("wxLiveChip").className=`status-chip ${valid.length?"normal":"caution"}`;$("wxLiveChip").textContent=valid.length?"LIVE":"AUTH / NO VALUES";$("wxSourceText").textContent=state.pro.forecastFetchedAt?`Fetched ${ageLabel(state.pro.forecastFetchedAt)} · BarentsWatch point adapters`:"No data";const cards=arr.map((s,i)=>`<div class="wx-sample ${wxStatus(s)}"><h4>${proEsc(sampleName(s,i))}</h4><div class="wx-row"><span>Hs</span><b>${wxValue(s.hs,"m")}</b></div><div class="wx-row"><span>Wind</span><b>${wxValue(s.windKn,"kn")}</b></div><div class="wx-row"><span>Current</span><b>${wxValue(s.currentKn,"kn")}</b></div><div class="wx-row"><span>Forecast</span><b>${proEsc((s.forecastTime||s.time||"—").toString().slice(0,16).replace("T"," "))}</b></div></div>`).join("");$("weatherStrip").className=arr.length?"weather-strip":"weather-strip empty";$("weatherStrip").innerHTML=cards||"No forecast samples returned.";$("intelWeatherStrip").className=arr.length?"weather-mini":"weather-mini empty";$("intelWeatherStrip").innerHTML=cards?arr.slice(0,4).map((s,i)=>`<div class="wx-sample ${wxStatus(s)}"><h4>${proEsc(sampleName(s,i))}</h4><div class="wx-row"><span>Hs</span><b>${wxValue(s.hs,"m")}</b></div><div class="wx-row"><span>Wind</span><b>${wxValue(s.windKn,"kn")}</b></div></div>`).join(""):"No forecast samples.";$("weatherRows").innerHTML=arr.map((s,i)=>`<tr><td>${proEsc(sampleName(s,i))}</td><td>${proEsc((s.forecastTime||s.time||"—").toString())}</td><td>${wxValue(s.hs,"m")}</td><td>${wxValue(s.windKn,"kn")}</td><td>${wxValue(s.currentKn,"kn")}</td><td><span class="status-chip ${wxStatus(s)}">${wxStatus(s)==="alert"?"EXCEEDS":"NORMAL"}</span></td><td>${proEsc(s.source||"BarentsWatch")}</td></tr>`).join("");$("opsWeather").textContent=hs.length?`Hs ${fmt(Math.max(...hs),1)} m`:valid.length?"Forecast loaded":"No numeric values";$("opsWeatherAge").textContent=ageLabel(state.pro.forecastFetchedAt);updateDataAge()}
async function loadRouteWeather(){const r=activeRoute();if(!r?.waypoints?.length)return alert("Create or load a route first.");try{$("wxLiveChip").className="status-chip info";$("wxLiveChip").textContent="LOADING";const data=await api("/api/forecast?route="+encodeURIComponent(JSON.stringify(r.waypoints)));state.pro.forecast=Array.isArray(data)?data:(data.items||[]);state.pro.forecastFetchedAt=nowIso();setHealth("healthBw","normal","LIVE");renderWeather()}catch(e){$("wxLiveChip").className="status-chip alert";$("wxLiveChip").textContent="ERROR";$("wxSourceText").textContent=`Forecast request failed: ${e.message}`;setHealth("healthBw","alert","ERR")}}
$("refreshWeather")?.addEventListener("click",loadRouteWeather);

// Intelligence visual map independent of original analysis
function initIntelMap(){if(state.pro.intelMap||!window.L||!$("intelMap"))return;state.pro.intelMap=L.map("intelMap",{zoomControl:false}).setView([59.15,10.35],7);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:19,attribution:"© OSM © CARTO"}).addTo(state.pro.intelMap)}
function renderIntelMap(){initIntelMap();if(!state.pro.intelMap)return;state.pro.intelLayers.forEach(x=>x.remove());state.pro.intelLayers=[];const r=activeRoute();if(!(r?.waypoints?.length>1))return;const line=L.polyline(r.waypoints.map(p=>[p.lat,p.lon]),{color:"#5bc8f4",weight:4}).addTo(state.pro.intelMap);state.pro.intelLayers.push(line);state.pro.intelMap.fitBounds(line.getBounds(),{padding:[25,25]});const corridor=state.vessel.corridor||5;state.pro.ais.filter(t=>routePointDistance({lat:+(t.latitude??t.lat),lon:+(t.longitude??t.lon)},r.waypoints)<=corridor).slice(0,80).forEach(t=>{const status=targetStatus(t),m=L.circleMarker([+(t.latitude??t.lat),+(t.longitude??t.lon)],{radius:4,color:status==="alert"?"#cf4f56":status==="caution"?"#c8952b":"#45c295",fillOpacity:.9}).addTo(state.pro.intelMap).bindTooltip(t.name||String(t.mmsi||"AIS"));state.pro.intelLayers.push(m)});$("intelMapStatus").className="status-chip normal";$("intelMapStatus").textContent="LIVE CONTEXT"}
$("runIntel")?.addEventListener("click",()=>setTimeout(async()=>{if(!state.pro.ais.length)await loadAisTraffic(false);if(!state.pro.forecast.length)await loadRouteWeather();renderIntelMap();renderWeather();},50));

// Fuel & ROB
function prefillProFromVessel(){if(state.vessel.fuelDay){if($("robCons"))$("robCons").value=state.vessel.fuelDay;if($("robFuel")&&!$("robFuel").value)$("robFuel").value=localStorage.getItem(PRO_KEYS.rob)||""}if(state.vessel.genRating){if($("goRating"))$("goRating").value=state.vessel.genRating}if(state.vessel.speed&&$("foSpeed"))$("foSpeed").value=state.vessel.speed;if(state.vessel.density&&$("bdnDensity"))$("bdnDensity").value=state.vessel.density}
$("calcROB")?.addEventListener("click",()=>{const rob=+$("robFuel").value,cons=+$("robCons").value,res=+$("robReserve").value||0,pass=+$("robPassageH").value||0;if(!(rob>=0&&cons>0))return;localStorage.setItem(PRO_KEYS.rob,String(rob));const usable=rob*(1-res/100),days=usable/cons,need=cons*pass/24,margin=usable-need;$("robOut").innerHTML=`Usable after reserve: <b>${fmt(usable,2)} m³</b><br>Endurance: <b>${duration(days*24)}</b><br>Passage requirement: <b>${fmt(need,2)} m³</b> · margin <b class="${margin<0?"data-alert":""}">${fmt(margin,2)} m³</b>`;updateOpsBoard()});
$("calcChangeover")?.addEventListener("click",()=>{const vol=+$("foLineVol").value,use=+$("foUseH").value,start=new Date($("foStart").value),speed=+$("foSpeed").value;if(!(vol>0&&use>0))return;const h=vol/use,end=isNaN(start)?null:new Date(start.getTime()+h*3600000),dist=Number.isFinite(speed)?speed*h:NaN;$("changeoverOut").innerHTML=`Calculated flushing time: <b>${duration(h)}</b>${end?`<br>Estimated completion: <b>${dateFmt(end)}</b>`:""}${Number.isFinite(dist)?`<br>Distance travelled at entered speed: <b>${fmt(dist,1)} NM</b>`:""}<br><small>Use only system volumes and changeover criteria applicable to the vessel and fuel procedure.</small>`});
$("calcTankTransfer")?.addEventListener("click",()=>{const s=+$("ttSource").value,d=+$("ttDest").value,cap=+$("ttCap").value,q=+$("ttQty").value,flow=+$("ttFlow").value,max=(+$("ttMax").value||90)/100;if(![s,d,cap,q,flow].every(Number.isFinite)||flow<=0)return;const allowed=Math.max(0,cap*max-d),actual=Math.min(q,s,allowed),mins=actual/flow*60,afterS=s-actual,afterD=d+actual;$("tankTransferOut").innerHTML=`Transfer possible: <b>${fmt(actual,2)} m³</b> of requested ${fmt(q,2)} m³<br>Estimated time: <b>${fmt(mins,0)} min</b><br>Source after: <b>${fmt(afterS,2)} m³</b> · destination after: <b>${fmt(afterD,2)} m³ (${fmt(afterD/cap*100,1)}%)</b>${actual<q?'<br><span class="data-alert">Requested quantity is constrained by source quantity or destination fill limit.</span>':''}`});
$("calcGenOpt")?.addEventListener("click",()=>{const load=+$("goLoad").value,rating=+$("goRating").value,count=Math.max(1,+$("goCount").value||1),min=+$("goMin").value||50,max=+$("goMax").value||85;if(!(load>=0&&rating>0))return;$("genOptOut").innerHTML=Array.from({length:count},(_,i)=>i+1).map(n=>{const pct=load/(n*rating)*100,cls=pct>100?"bad":pct>=min&&pct<=max?"good":"caution",label=pct>100?"OVERLOAD":pct<min?"LOW LOAD":pct>max?"HIGH LOAD":"TARGET RANGE";return`<div class="scenario ${cls}"><span>${n} DG${n>1?"s":""} running</span><strong>${fmt(pct,1)} % each</strong><b>${label}</b></div>`}).join("")});

// Electrical
$("calc3P")?.addEventListener("click",()=>{const v=+$("elV").value,a=+$("elA").value,pf=+$("elPF").value,eff=(+$("elEff").value||100)/100;if(!(v>0&&a>=0&&pf>=0))return;const kva=Math.sqrt(3)*v*a/1000,kw=kva*pf*eff;$("el3POut").innerHTML=`Apparent power: <b>${fmt(kva,1)} kVA</b><br>Active output after entered efficiency: <b>${fmt(kw,1)} kW</b>`});
$("calcImbalance")?.addEventListener("click",()=>{const a=[+$("imL1").value,+$("imL2").value,+$("imL3").value];if(!a.every(Number.isFinite))return;const avg=a.reduce((x,y)=>x+y,0)/3,dev=Math.max(...a.map(x=>Math.abs(x-avg))),pct=avg?dev/avg*100:0;$("imbalanceOut").innerHTML=`Average current: <b>${fmt(avg,1)} A</b><br>Maximum deviation: <b>${fmt(dev,1)} A</b> · imbalance <b>${fmt(pct,2)} %</b><br><small>Assess limits against the applicable equipment/vendor criteria.</small>`});
$("calcBattery")?.addEventListener("click",()=>{const v=+$("bbV").value,ah=+$("bbAh").value,s=+$("bbStart").value,m=+$("bbMin").value,load=+$("bbLoad").value,eff=(+$("bbEff").value||100)/100;if(!(v>0&&ah>0&&load>0))return;const bank=v*ah/1000,usable=bank*Math.max(0,s-m)/100*eff,h=usable/(load/1000);$("batteryOut").innerHTML=`Nominal bank energy: <b>${fmt(bank,2)} kWh</b><br>Usable to entered minimum SOC: <b>${fmt(usable,2)} kWh</b><br>Idealized endurance: <b>${duration(h)}</b>`});
$("calcShore")?.addEventListener("click",()=>{const v=+$("shoreV").value,a=+$("shoreA").value,pf=+$("shorePF").value,load=+$("shoreLoad").value;if(!(v>0&&a>=0&&pf>=0))return;const kva=Math.sqrt(3)*v*a/1000,kw=kva*pf,margin=kw-(load||0);$("shoreOut").innerHTML=`Available: <b>${fmt(kva,1)} kVA / ${fmt(kw,1)} kW</b>${Number.isFinite(load)?`<br>Entered load margin: <b class="${margin<0?"data-alert":""}">${fmt(margin,1)} kW</b>`:""}`});
const shoreItems=["Voltage / frequency verified","Phase sequence verified","Earth / bonding arrangement checked","Vessel breaker open before connection","Load reduction / transfer plan agreed","Connection inspected before energizing"];
function renderShoreChecklist(){const saved=store.get(PRO_KEYS.shore,{});$("shoreChecklist").innerHTML=shoreItems.map((x,i)=>`<label><input type="checkbox" data-shore="${i}" ${saved[i]?"checked":""}>${x}</label>`).join("");$("shoreChecklist").querySelectorAll("[data-shore]").forEach(c=>c.addEventListener("change",()=>{const s=store.get(PRO_KEYS.shore,{});s[c.dataset.shore]=c.checked;store.set(PRO_KEYS.shore,s)}))}
function loadIR(){return store.get(PRO_KEYS.ir,[])}
function renderIR(){const rows=loadIR();$("irRows").innerHTML=rows.map(x=>`<tr><td>${proEsc(x.date)}</td><td>${proEsc(x.equipment)}</td><td>${fmt(+x.mohm,1)}</td><td>${proEsc(x.voltage||"—")}</td><td>${proEsc(x.notes||"")}</td><td><button class="danger-soft small" data-del-ir="${x.id}">×</button></td></tr>`).join("");$("irRows").querySelectorAll("[data-del-ir]").forEach(b=>b.addEventListener("click",()=>{store.set(PRO_KEYS.ir,loadIR().filter(x=>x.id!==b.dataset.delIr));renderIR()}))}
$("addIR")?.addEventListener("click",()=>{const e={id:uuid(),date:$("irDate").value||new Date().toISOString().slice(0,10),equipment:$("irEquipment").value.trim(),mohm:+$("irMohm").value,voltage:$("irVoltage").value,notes:$("irNotes").value.trim()};if(!e.equipment||!Number.isFinite(e.mohm))return;store.set(PRO_KEYS.ir,[e,...loadIR()]);renderIR()});
$("exportIR")?.addEventListener("click",()=>{const rows=loadIR(),csv=["date,equipment,mohm,test_voltage,notes",...rows.map(x=>[x.date,x.equipment,x.mohm,x.voltage,x.notes].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))].join("\n");download("bridgekit-insulation-log.csv",csv,"text/csv")});

// Equipment cards
function loadEquipment(){return store.get(PRO_KEYS.equipment,[])}
function equipmentStatus(x){const h=+x.hours,n=+x.next;if(!Number.isFinite(h)||!Number.isFinite(n)||!n)return"normal";const rem=n-h;if(rem<0)return"overdue";if(rem<=Math.max(10,n*.01))return"due";return"normal"}
function renderEquipment(){const arr=loadEquipment();$("equipmentCards").innerHTML=arr.map(x=>{const st=equipmentStatus(x),rem=Number.isFinite(+x.next)&&Number.isFinite(+x.hours)?+x.next-+x.hours:NaN;return`<article class="equipment-card ${st}"><div class="card-head"><div><span class="round-icon">${iconUse(x.type==="Generator"?"generator":x.type==="Pump"?"pump":x.type==="Switchboard"?"bolt":"equipment")}</span><span><h3>${proEsc(x.name)}</h3><p>${proEsc(x.type)}</p></span></div><button class="danger-soft small" data-del-eq="${x.id}">×</button></div><div class="equipment-meta"><div><small>RATING</small><strong>${proEsc(x.rating||"—")}</strong></div><div><small>RUNNING HOURS</small><strong>${Number.isFinite(+x.hours)?fmt(+x.hours,0)+" h":"—"}</strong></div><div><small>NEXT SERVICE</small><strong>${Number.isFinite(+x.next)?fmt(+x.next,0)+" h":"—"}</strong></div><div><small>REMAINING</small><strong>${Number.isFinite(rem)?fmt(rem,0)+" h":"—"}</strong></div></div><p class="helper">${proEsc(x.notes||"")}</p></article>`}).join("")||'<div class="source-status">No equipment cards yet.</div>';$("equipmentCards").querySelectorAll("[data-del-eq]").forEach(b=>b.addEventListener("click",()=>{store.set(PRO_KEYS.equipment,loadEquipment().filter(x=>x.id!==b.dataset.delEq));renderEquipment()}))}
$("addEquipment")?.addEventListener("click",()=>{const x={id:uuid(),name:$("eqName").value.trim(),type:$("eqType").value,rating:$("eqRating").value.trim(),hours:+$("eqHours").value,next:+$("eqNext").value,notes:$("eqNotes").value.trim()};if(!x.name)return;store.set(PRO_KEYS.equipment,[x,...loadEquipment()]);renderEquipment()});
$("exportEquipment")?.addEventListener("click",()=>{const a=loadEquipment(),csv=["name,type,rating,hours,next_service,notes",...a.map(x=>[x.name,x.type,x.rating,x.hours,x.next,x.notes].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))].join("\n");download("bridgekit-equipment.csv",csv,"text/csv")});

// Limits
function fillLimits(){const v=state.vessel;[["limHs","maxHs"],["limWind","maxWind"],["limCurrent","maxCurrent"],["limUkc","minUkc"],["limCpa","cpa"],["limCorridor","corridor"],["limDgMin","genTargetMin"],["limDgMax","genTargetMax"],["limEssMin","essMinSoc"],["limStale","staleMinutes"]].forEach(([id,k])=>{if($(id))$(id).value=v[k]??({genTargetMin:50,genTargetMax:85,essMinSoc:20,staleMinutes:10}[k]??"")});renderLimitsBoard()}
function renderLimitsBoard(){if(!$("limitsBoard"))return;const v=state.vessel;const d=[["Max Hs",v.maxHs,"m"],["Max wind",v.maxWind,"kn"],["Max current",v.maxCurrent,"kn"],["Min UKC",v.minUkc,"m"],["CPA alert",v.cpa,"NM"],["AIS corridor",v.corridor,"NM"],["DG target",v.genTargetMin&&v.genTargetMax?`${v.genTargetMin}–${v.genTargetMax}`:null,"%"],["ESS min SOC",v.essMinSoc,"%"],["Stale data",v.staleMinutes,"min"]];$("limitsBoard").innerHTML=d.map(([n,x,u])=>`<div class="limit-tile"><small>${n}</small><strong>${x??"—"}${x!==undefined&&x!==null?" "+u:""}</strong></div>`).join("")}
$("saveLimits")?.addEventListener("click",()=>{const map={maxHs:"limHs",maxWind:"limWind",maxCurrent:"limCurrent",minUkc:"limUkc",cpa:"limCpa",corridor:"limCorridor",genTargetMin:"limDgMin",genTargetMax:"limDgMax",essMinSoc:"limEssMin",staleMinutes:"limStale"};Object.entries(map).forEach(([k,id])=>state.vessel[k]=+$(id).value||0);store.set(KEYS.vessel,state.vessel);const i=state.vessels.findIndex(x=>x.id===state.vessel.id);if(i>=0){state.vessels[i]=JSON.parse(JSON.stringify(state.vessel));store.set(KEYS.vessels,state.vessels)}renderLimits();renderLimitsBoard();alert("Operational limits saved to active vessel profile.")});

// Watch board + data age
function currentWatchPosition(){const lat=+$("watchLat")?.value,lon=+$("watchLon")?.value;if(Number.isFinite(lat)&&Number.isFinite(lon))return{lat,lon};const r=activeRoute();return r?.waypoints?.[0]||null}
function updateDataAge(){if(!$("dataAgePanel"))return;const rows=[["AIS",state.pro.aisFetchedAt],["Weather",state.pro.forecastFetchedAt],["Warnings",state.pro.warningsFetchedAt]];$("dataAgePanel").innerHTML=rows.map(([n,t])=>`<div class="age-row"><span>${n}</span><b>${ageLabel(t)}</b><span class="status-chip ${t?staleClass(t):"unavailable"}">${!t?"NO DATA":staleClass(t)==="normal"?"CURRENT":"STALE"}</span></div>`).join("")}
function updateWatch(){const pos=currentWatchPosition(),r=activeRoute(),m=routeMetrics(r),v=state.vessel,rob=+$("watchRob")?.value||+localStorage.getItem(PRO_KEYS.rob)||0,cons=v.fuelDay||0,end=cons?rob/cons:NaN,aisCount=r?.waypoints?.length>1?state.pro.ais.filter(t=>routePointDistance({lat:+(t.latitude??t.lat),lon:+(t.longitude??t.lon)},r.waypoints)<=(v.corridor||5)).length:state.pro.ais.length,hs=state.pro.forecast.map(x=>+x.hs).filter(Number.isFinite),wind=state.pro.forecast.map(x=>+x.windKn).filter(Number.isFinite);const cells=[["Position",pos?`${ddm(pos.lat,true)} / ${ddm(pos.lon,false)}`:"—",`${fmt(+$("watchSog")?.value,1)} kn · ${fmt(+$("watchCog")?.value,0)}°`],["Active voyage",state.voyages[0]?.name||"—",r?.name||"No active route"],["AIS traffic",`${aisCount} target(s)`,state.pro.aisFetchedAt?ageLabel(state.pro.aisFetchedAt):"Not loaded"],["Weather",hs.length?`Hs ${fmt(Math.max(...hs),1)} m`:"—",wind.length?`Max wind ${fmt(Math.max(...wind),1)} kn`:"Not loaded"],["Warnings",`${state.pro.warnings.length||0} loaded`,state.pro.warningsFetchedAt?ageLabel(state.pro.warningsFetchedAt):"Not loaded"],["Fuel ROB",rob?`${fmt(rob,2)} m³`:"—",Number.isFinite(end)?`Endurance ${duration(end*24)}`:"Set ROB / consumption"],["Running DG",$("watchDG")?.value||"—",v.genRating?`${fmt(v.genRating,0)} kW rating profile`:"No generator default"],["Passage",r?.waypoints?.length>1?`${fmt(m.distance,1)} NM`:"—",r?.waypoints?.length>1?duration(m.hours):"No route"]];$("watchGrid").innerHTML=cells.map(([a,b,c])=>`<div class="watch-cell"><small>${a}</small><strong>${proEsc(b)}</strong><span>${proEsc(c)}</span></div>`).join("");updateDataAge()}
$("refreshWatch")?.addEventListener("click",updateWatch);$("printWatch")?.addEventListener("click",()=>window.print());

// Warnings cache: keep existing loadWarnings but add a parallel loader for dashboard
async function proLoadWarnings(){try{const r=await fetch("https://api.kystverket.no/data/navigationwarnings/coastal/");if(!r.ok)throw new Error();const j=await r.json();state.pro.warnings=Array.isArray(j)?j:(j.items||j.features||[]);state.pro.warningsFetchedAt=nowIso();setHealth("healthWarn","normal","LIVE");const route=activeRoute(),corr=state.vessel.corridor||5,geo=route?.waypoints?.length>1?state.pro.warnings.filter(w=>{const p=warningPoint(w);return p&&routePointDistance(p,route.waypoints)<=corr}).length:state.pro.warnings.length;$("opsWarnings").textContent=`${geo} relevant / ${state.pro.warnings.length} loaded`;$("opsWarnAge").textContent=ageLabel(state.pro.warningsFetchedAt);updateDataAge()}catch{setHealth("healthWarn","unavailable","OFF")}}
$("loadCoastal")?.addEventListener("click",()=>setTimeout(proLoadWarnings,50));

// Dashboard / operations
function updateOpsBoard(){const v=state.vessel,vy=state.voyages[0],r=activeRoute();$("opsVessel").textContent=v.name||"Not configured";$("opsVesselMeta").textContent=v.draft?`Draft ${fmt(v.draft,2)} m · service ${fmt(v.speed,1)} kn`:"Add particulars and limits";$("opsVoyage").textContent=vy?.name||"No active voyage";$("opsVoyageMeta").textContent=r?.waypoints?.length>1?`${fmt(routeMetrics(r).distance,1)} NM · ${r.waypoints.length} WPs`:"Create or load a route";const rob=+localStorage.getItem(PRO_KEYS.rob)||0;$("opsEndurance").textContent=rob&&v.fuelDay?duration(rob/v.fuelDay*24):"—";if(!state.pro.aisFetchedAt)$("opsAisAge").textContent="Not loaded";if(!state.pro.forecastFetchedAt)$("opsWeatherAge").textContent="Not loaded";if(!state.pro.warningsFetchedAt)$("opsWarnAge").textContent="Not loaded"}

// Reports
function printOpsReport(){const w=window.open("","_blank");const r=activeRoute(),m=routeMetrics(r),hs=state.pro.forecast.map(x=>+x.hs).filter(Number.isFinite),wind=state.pro.forecast.map(x=>+x.windKn).filter(Number.isFinite);w.document.write(`<!doctype html><html><head><title>BridgeKit Operations Snapshot</title><style>body{font-family:Aptos,Arial;margin:34px;color:#17324a}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.box{padding:12px;border:1px solid #ccd8e1}.small{color:#6f8293;font-size:12px}.warn{margin-top:20px;padding:12px;border-left:4px solid #c8952b;background:#fff8e9}</style></head><body><h1>Operations Snapshot</h1><p class="small">Generated ${new Date().toISOString().replace("T"," ").slice(0,19)} UTC</p><div class="grid"><div class="box"><b>Vessel</b><br>${proEsc(state.vessel.name||"—")}</div><div class="box"><b>Route</b><br>${proEsc(r?.name||"—")}</div><div class="box"><b>Distance</b><br>${r?.waypoints?.length>1?fmt(m.distance,1)+" NM":"—"}</div><div class="box"><b>AIS targets loaded</b><br>${state.pro.ais.length}</div><div class="box"><b>Max Hs</b><br>${hs.length?fmt(Math.max(...hs),1)+" m":"—"}</div><div class="box"><b>Max wind</b><br>${wind.length?fmt(Math.max(...wind),1)+" kn":"—"}</div></div><h2>Data age</h2><p>AIS: ${ageLabel(state.pro.aisFetchedAt)}<br>Weather: ${ageLabel(state.pro.forecastFetchedAt)}<br>Warnings: ${ageLabel(state.pro.warningsFetchedAt)}</p><div class="warn"><b>Planning aid only.</b> Verify all operational decisions against approved vessel systems, official publications, procedures and responsible officers.</div><script>print()<\/script></body></html>`);w.document.close()}
$("reportPassage")?.addEventListener("click",()=>{const v=state.voyages[0];if(v)printPassageReport(v);else alert("Create a voyage first.")});$("reportOps")?.addEventListener("click",printOpsReport);$("reportBunker")?.addEventListener("click",()=>$("printBunker")?.click());$("reportData")?.addEventListener("click",()=>$("exportLocal")?.click());

// Page lifecycle
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.page;setTimeout(()=>{if(p==='ais'){initAisMap();state.pro.aisMap?.invalidateSize();if(!state.pro.ais.length)loadAisTraffic(true)}if(p==='weather'&&!state.pro.forecast.length)loadRouteWeather();if(p==='limits')fillLimits();if(p==='equipment')renderEquipment();if(p==='watch')updateWatch();if(p==='electrical'){renderIR();renderShoreChecklist()}if(p==='fuel')prefillProFromVessel();if(p==='intelligence'){initIntelMap();state.pro.intelMap?.invalidateSize();renderIntelMap();renderWeather()}},70)}));

// Init pro workspace
function proInit(){applyLanguage(state.settings.language||"en");applyRole(state.pro.role);renderPinned();renderFavoriteSettings();refreshSystemHealth();renderEquipment();renderIR();renderShoreChecklist();fillLimits();prefillProFromVessel();updateOpsBoard();updateDataAge();proLoadWarnings();$("irDate").value=new Date().toISOString().slice(0,10);$("foStart").value=isoLocalNow();setInterval(()=>{refreshSystemHealth();updateDataAge()},300000)}
proInit();
