(() => {'use strict';
const RELEASE={version:'8.6.0',released:'2026-10-05',build:'20261005-v8-6-0-energy',history:[{version:'8.6.0',date:'2026-10-05',title:'Fuel & Energy workflows',items:['Vessel Profile 2.0','Fuel & Energy Log','Alternative-fuel and ESS model','Connected fuel/bunkering workflows','Analytics v3','Offline/PWA polish']},{version:'8.5.8',date:'2026-10-04',title:'Home refinement',items:['Coherent line icons','Balanced Common jobs','Sidebar polish']},{version:'8.5.7',date:'2026-10-03',title:'Release hardening',items:['Technical health','Data freshness','Update flow']}]};window.__MARINE_TOOLS_RELEASE=RELEASE;
const API='https://api.marinetools.app',realFetch=window.fetch.bind(window);function parts(v){return String(v||'').split('.').map(x=>parseInt(x)||0)}function newer(a,b){a=parts(a);b=parts(b);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false}return false}
window.fetch=async function(input,init){let u;try{u=new URL(typeof input==='string'?input:input?.url,location.href)}catch{}if(u?.origin===API&&u.pathname==='/api/analytics/event'&&typeof init?.body==='string'){try{const b=JSON.parse(init.body);b.version=RELEASE.version;init={...init,body:JSON.stringify(b)}}catch{}}return realFetch(input,init)};
function loadSidebar(){if(!document.getElementById('mtSidebar858Css')){const l=document.createElement('link');l.id='mtSidebar858Css';l.rel='stylesheet';l.href='sidebar-v858.css?v=20261005-v860';document.head.appendChild(l)}if(!document.getElementById('mtSidebar858Js')){const s=document.createElement('script');s.id='mtSidebar858Js';s.src='sidebar-v858.js?v=20261005-v860';s.defer=true;document.head.appendChild(s)}if(!document.getElementById('mtSidebarActiveV860')){const s=document.createElement('script');s.id='mtSidebarActiveV860';s.src='sidebar-active-v860.js?v=20261005-v860-active-1';s.defer=true;document.head.appendChild(s)}}
function inject(){const footer=document.querySelector('.site-footer span:first-child');if(footer&&!footer.querySelector('.mt-release-badge')){const b=document.createElement('span');b.className='mt-release-badge';b.textContent='v'+RELEASE.version;footer.appendChild(b)}const items=document.querySelector('.nav-project-items');if(items&&!document.getElementById('mtWhatsNew')){const b=document.createElement('button');b.id='mtWhatsNew';b.className='nav-btn';b.innerHTML='<span>↻</span>What\'s new';b.onclick=()=>alert(RELEASE.history.map(r=>'v'+r.version+' · '+r.title+'\n- '+r.items.join('\n- ')).join('\n\n'));items.prepend(b)}}
async function initSW(){if(!('serviceWorker'in navigator)||location.protocol!=='https:')return;try{const r=await navigator.serviceWorker.register('/sw.js?v='+RELEASE.build,{scope:'/'});if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'});setTimeout(()=>r.update().catch(()=>{}),1500)}catch{}}
async function check(){if(!navigator.onLine)return;try{const r=await realFetch(API+'/api/release',{cache:'no-store'}),d=await r.json();if(d?.version&&newer(d.version,RELEASE.version))console.info('MarineTools update available',d.version)}catch{}}
const s=document.createElement('style');s.textContent='.mt-release-badge{display:inline-flex;border:1px solid rgba(120,160,190,.28);border-radius:999px;padding:3px 8px;font-size:11px;color:#9fb8c8;margin-left:7px}';document.head.appendChild(s);loadSidebar();document.addEventListener('DOMContentLoaded',()=>{inject();initSW();check()});})();
