
const TOKEN_URL="https://id.barentswatch.no/connect/token";
const AIS_LATEST_URL="https://live.ais.barentswatch.no/v1/latest/combined";
const BW_API_ROOT="https://www.barentswatch.no/bwapi/";
let tokenCache={}, forecastCache=new Map(), paramStyle={};
const cors={"access-control-allow-origin":"*","access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"content-type":"application/json;charset=utf-8"}});
async function getToken(scope,env){const c=tokenCache[scope];if(c&&c.expires>Date.now()+60000)return c.value;const id=scope==="ais"?env.BW_AIS_CLIENT_ID:env.BW_API_CLIENT_ID,secret=scope==="ais"?env.BW_AIS_CLIENT_SECRET:env.BW_API_CLIENT_SECRET;if(!id||!secret)throw new Error(`Missing ${scope.toUpperCase()} credentials in Worker secrets`);const body=new URLSearchParams({grant_type:"client_credentials",client_id:id,client_secret:secret,scope});const r=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});if(!r.ok){const d=await r.text().catch(()=>"");throw new Error(`BarentsWatch ${scope} token request failed (${r.status})${d?`: ${d.slice(0,240)}`:""}`)}const j=await r.json();tokenCache[scope]={value:j.access_token,expires:Date.now()+(j.expires_in||3600)*1000};return j.access_token}
async function authStatus(env){const result={ais:{configured:Boolean(env.BW_AIS_CLIENT_ID&&env.BW_AIS_CLIENT_SECRET),authenticated:false},api:{configured:Boolean(env.BW_API_CLIENT_ID&&env.BW_API_CLIENT_SECRET),authenticated:false}};for(const s of ["ais","api"]){try{if(result[s].configured){await getToken(s,env);result[s].authenticated=true}}catch(e){result[s].error=e.message}}return result}
function parseBounds(url){const n=k=>Number(url.searchParams.get(k)),b={minLat:n("minLat"),maxLat:n("maxLat"),minLon:n("minLon"),maxLon:n("maxLon")};return Object.values(b).every(Number.isFinite)?b:null}
function inBounds(v,b){const lat=Number(v.latitude??v.lat),lon=Number(v.longitude??v.lon);return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=b.minLat&&lat<=b.maxLat&&lon>=b.minLon&&lon<=b.maxLon}
async function latestAis(url,env){const access=await getToken("ais",env),r=await fetch(AIS_LATEST_URL,{headers:{authorization:`Bearer ${access}`}});if(!r.ok){const d=await r.text().catch(()=>"");throw new Error(`AIS latest request failed (${r.status})${d?`: ${d.slice(0,240)}`:""}`)}const all=await r.json();if(!Array.isArray(all))return all;const b=parseBounds(url);return b?all.filter(v=>inBounds(v,b)):all}
const ENDPOINTS={wave:"v1/waveforecastpoint/nearest/all",wind:"v1/windforecastpoint/nearest/all",current:"v1/seacurrent/nearest/all"};
function flatten(obj,prefix="",out={}){if(obj==null)return out;if(Array.isArray(obj)){obj.slice(0,8).forEach((v,i)=>flatten(v,`${prefix}[${i}]`,out));return out}if(typeof obj==="object"){for(const [k,v] of Object.entries(obj))flatten(v,prefix?`${prefix}.${k}`:k,out);return out}out[prefix]=obj;return out}
function matchNumber(flat,patterns){for(const [k,v] of Object.entries(flat)){if(typeof v!=="number"&&!Number.isFinite(Number(v)))continue;if(patterns.some(p=>p.test(k)))return{key:k,value:Number(v)}}return null}
function matchText(flat,patterns){for(const [k,v] of Object.entries(flat)){if(typeof v!=="string")continue;if(patterns.some(p=>p.test(k)))return{key:k,value:v}}return null}
function chooseForecastItem(data){if(Array.isArray(data))return data[0]||{};if(Array.isArray(data?.items))return data.items[0]||{};if(Array.isArray(data?.data))return data.data[0]||{};return data||{}}
function speedToKn(hit,flat){if(!hit)return null;const unit=matchText(flat,[/unit/i,/speedunit/i])?.value?.toLowerCase()||"";if(/knot|\bkn\b/.test(unit)||/knot|\.kn\b/i.test(hit.key))return hit.value;if(/m\/s|mps|meter.*second/.test(unit)||/mps|meterpersecond/i.test(hit.key))return hit.value*1.943844;return null}
function normalize(kind,data){const item=chooseForecastItem(data),flat=flatten(item),time=matchText(flat,[/forecast.*time/i,/valid.*time/i,/time$/i,/date/i])?.value||null;if(kind==="wave"){const hs=matchNumber(flat,[/significant.*wave.*height/i,/wave.*height/i,/(^|\.)hs$/i]);return{hs:hs?.value??null,forecastTime:time,rawKey:hs?.key||null}}if(kind==="wind"){const sp=matchNumber(flat,[/wind.*speed/i,/speed.*wind/i,/velocity/i,/speed$/i]),dir=matchNumber(flat,[/wind.*direction/i,/direction.*wind/i,/direction$/i]);return{windKn:speedToKn(sp,flat),windRaw:sp?.value??null,windDirection:dir?.value??null,forecastTime:time,rawKey:sp?.key||null}}const sp=matchNumber(flat,[/current.*speed/i,/speed.*current/i,/velocity/i,/speed$/i]),dir=matchNumber(flat,[/current.*direction/i,/direction.*current/i,/direction$/i]);return{currentKn:speedToKn(sp,flat),currentRaw:sp?.value??null,currentDirection:dir?.value??null,forecastTime:time,rawKey:sp?.key||null}}
async function bwPoint(kind,lat,lon,env){const key=`${kind}:${lat.toFixed(3)}:${lon.toFixed(3)}`,cached=forecastCache.get(key);if(cached&&cached.expires>Date.now())return cached.data;const access=await getToken("api",env),path=ENDPOINTS[kind],styles=paramStyle[kind]?[paramStyle[kind]]:["latitude","lat","coords"];let lastStatus=0,lastBody="";for(const style of styles){const qs=new URLSearchParams();if(style==="latitude"){qs.set("latitude",lat);qs.set("longitude",lon)}else if(style==="lat"){qs.set("lat",lat);qs.set("lon",lon)}else{qs.set("coordinates",`${lon},${lat}`)}const r=await fetch(`${BW_API_ROOT}${path}?${qs}`,{headers:{authorization:`Bearer ${access}`,accept:"application/json"}});lastStatus=r.status;const text=await r.text();lastBody=text;if(r.ok){paramStyle[kind]=style;let raw;try{raw=JSON.parse(text)}catch{raw=text}const data={ok:true,kind,endpoint:path,style,...normalize(kind,raw)};forecastCache.set(key,{data,expires:Date.now()+5*60*1000});return data}}return{ok:false,kind,endpoint:path,status:lastStatus,error:lastBody.slice(0,240)}}
function routeSamples(route,max=8){if(!Array.isArray(route)||!route.length)return[];if(route.length<=max)return route;const out=[];for(let i=0;i<max;i++)out.push(route[Math.round(i*(route.length-1)/(max-1))]);return out}
async function forecast(url,env){await getToken("api",env);const raw=url.searchParams.get("route"),route=raw?JSON.parse(raw):[];if(!Array.isArray(route))return[];const pts=routeSamples(route,8);return Promise.all(pts.map(async(p,i)=>{const lat=Number(p.lat),lon=Number(p.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return{index:i,source:"invalid-point"};const [w,wi,c]=await Promise.all([bwPoint("wave",lat,lon,env),bwPoint("wind",lat,lon,env),bwPoint("current",lat,lon,env)]);return{index:i,name:p.name||`P${i+1}`,lat,lon,hs:w.hs??null,windKn:wi.windKn??null,windRaw:wi.windRaw??null,windDirection:wi.windDirection??null,currentKn:c.currentKn??null,currentRaw:c.currentRaw??null,currentDirection:c.currentDirection??null,forecastTime:w.forecastTime||wi.forecastTime||c.forecastTime||null,source:"BarentsWatch point forecast",diagnostics:{wave:w.ok?"ok":w.status,wind:wi.ok?"ok":wi.status,current:c.ok?"ok":c.status}}}))}
const ALLOWED={wave:ENDPOINTS.wave,wind:ENDPOINTS.wind,current:ENDPOINTS.current};async function probe(url,env){const kind=url.searchParams.get("endpoint"),path=ALLOWED[kind];if(!path)return{error:"Unsupported endpoint",allowed:Object.keys(ALLOWED)};const access=await getToken("api",env),qs=new URLSearchParams(url.searchParams);qs.delete("endpoint");const r=await fetch(`${BW_API_ROOT}${path}${qs.toString()?`?${qs}`:""}`,{headers:{authorization:`Bearer ${access}`,accept:"application/json"}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}return{upstreamStatus:r.status,endpoint:path,data:body}}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:cors});const url=new URL(request.url);try{if(url.pathname==="/api/health")return json({status:"ok",service:"BridgeKit API",capabilities:["ais","barentswatch-api","route-forecast"]});if(url.pathname==="/api/auth/status")return json(await authStatus(env));if(url.pathname==="/api/ais/latest")return json(await latestAis(url,env));if(url.pathname==="/api/forecast")return json(await forecast(url,env));if(url.pathname==="/api/barentswatch/probe")return json(await probe(url,env));return json({error:"Not found"},404)}catch(e){return json({error:e.message},500)}}};
