import previousWorker from "./worker-v853-fastland.js";

const MET_LOCATION_URL="https://api.met.no/weatherapi/locationforecast/2.0/compact";
const MET_OCEAN_URL="https://api.met.no/weatherapi/oceanforecast/2.0/complete";
const NOAA_ROOT="https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod";
const NOAA_FILTER="https://nomads.ncep.noaa.gov/cgi-bin/filter_gfswave.pl";
const USER_AGENT="MarineTools/8.5.4 contact@marinetools.app";
const cors={"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type"};
const weatherCache=new Map(),cycleCache={value:null,expires:0},waveCache=new Map();

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"content-type":"application/json;charset=utf-8","cache-control":"no-store"}})}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function msToKn(v){return v==null?null:v*1.943844}
function rad(x){return x*Math.PI/180}
function pad(n,w=2){return String(n).padStart(w,"0")}
function distanceNm(a,b){if(!a||!b)return null;const R=3440.065,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function rows(d){return Array.isArray(d?.properties?.timeseries)?d.properties.timeseries:[]}
function geometry(d){const c=d?.geometry?.coordinates;if(!Array.isArray(c)||c.length<2)return null;const lon=num(c[0]),lat=num(c[1]),alt=num(c[2]);return lon==null||lat==null?null:{lat,lon,alt}}
function detail(row,key){return num(row?.data?.instant?.details?.[key])}
function periodDetail(row,key){for(const p of ["next_1_hours","next_6_hours","next_12_hours"]){const v=num(row?.data?.[p]?.details?.[key]);if(v!=null)return v}return null}
function periodSummary(row,key){for(const p of ["next_1_hours","next_6_hours","next_12_hours"]){const v=row?.data?.[p]?.summary?.[key];if(v!=null)return v}return null}
function selectFuture(series,limit){const now=Date.now()-45*60*1000,f=series.filter(r=>{const t=Date.parse(r?.time||"");return Number.isFinite(t)&&t>=now});return(f.length?f:series).slice(0,limit)}
function nearest(series,time,maxMs=90*60*1000){if(!series?.length)return null;const target=Date.parse(time||"");if(!Number.isFinite(target))return series[0]||null;let best=null,d=Infinity;for(const row of series){const t=Date.parse(row?.time||"");if(!Number.isFinite(t))continue;const q=Math.abs(t-target);if(q<d){d=q;best=row}}return d<=maxMs?best:null}
function combined(locationRow,oceanRow){return{forecastTime:locationRow?.time||oceanRow?.time||null,hs:detail(oceanRow,"sea_surface_wave_height"),waveDirection:detail(oceanRow,"sea_surface_wave_from_direction"),wavePeriod:detail(oceanRow,"sea_surface_wave_period_at_variance_spectral_density_maximum"),windKn:msToKn(detail(locationRow,"wind_speed")),windDirection:detail(locationRow,"wind_from_direction"),airTemp:detail(locationRow,"air_temperature"),seaTemp:detail(oceanRow,"sea_water_temperature"),precipitation:periodDetail(locationRow,"precipitation_amount"),symbolCode:periodSummary(locationRow,"symbol_code"),source:"MET Norway"}}

async function timedFetch(url,init={},timeoutMs=4500){const ac=new AbortController(),timer=setTimeout(()=>ac.abort("timeout"),timeoutMs);try{return await fetch(url,{...init,signal:ac.signal,headers:{"user-agent":USER_AGENT,...(init.headers||{})}})}finally{clearTimeout(timer)}}
async function fetchMet(url,timeoutMs=3500){try{const r=await timedFetch(url,{headers:{accept:"application/json"}},timeoutMs),text=await r.text();let data=null;try{data=JSON.parse(text)}catch{}return r.ok?{ok:true,status:r.status,data}:{ok:false,status:r.status,error:(data?.error||text||"").slice(0,240),data}}catch(err){return{ok:false,status:"timeout",error:String(err?.message||err),data:null}}}
function inlandForecast(locationRows,limit){return selectFuture(locationRows,limit).map(r=>combined(r,null)).map(r=>({...r,hs:null,waveDirection:null,wavePeriod:null,seaTemp:null}))}

function cycleCandidates(now=new Date()){const t=new Date(now);t.setUTCMinutes(0,0,0);t.setUTCHours(Math.floor(t.getUTCHours()/6)*6);const out=[];for(let i=0;i<5;i++){const d=new Date(t.getTime()-i*6*3600000);out.push({date:`${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}`,hour:pad(d.getUTCHours()),ms:Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours())})}return out}
async function latestCycle(){if(cycleCache.value&&cycleCache.expires>Date.now())return cycleCache.value;for(const c of cycleCandidates()){const file=`gfswave.t${c.hour}z.global.0p25.f003.grib2`,dir=`/gfs.${c.date}/${c.hour}/wave/gridded`,base=`${NOAA_ROOT}${dir}/${file}`;try{const r=await timedFetch(`${base}.idx`,{headers:{accept:"text/plain"}},2500);if(r.ok){const text=await r.text();if(/:HTSGW:/.test(text)){const v={...c,dir};cycleCache.value=v;cycleCache.expires=Date.now()+15*60*1000;return v}}}catch{}}return null}
function u32(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(o,false)}
function i16(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getInt16(o,false)}
function f32(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getFloat32(o,false)}
function gribSections(bytes){if(bytes.length<20||String.fromCharCode(...bytes.slice(0,4))!=="GRIB")throw new Error("Not GRIB2");const out={};let p=16;while(p+5<=bytes.length){if(String.fromCharCode(...bytes.slice(p,p+4))==="7777")break;const len=u32(bytes,p),no=bytes[p+4];if(!(len>=5)||p+len>bytes.length)throw new Error("Invalid GRIB2 section");out[no]={start:p,length:len};p+=len}return out}
function readBits(bytes,bitOffset,width){let v=0;for(let i=0;i<width;i++){const q=bitOffset+i,byte=bytes[q>>3],bit=7-(q&7);v=v*2+((byte>>bit)&1)}return v}
function decodeSimpleFirst(bytes){const s=gribSections(bytes),s5=s[5],s6=s[6],s7=s[7];if(!s5||!s7)throw new Error("Missing GRIB2 data");const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),template=dv.getUint16(s5.start+9,false),points=u32(bytes,s5.start+5);if(template!==0)throw new Error(`Unsupported packing ${template}`);const reference=f32(bytes,s5.start+11),binaryScale=i16(bytes,s5.start+15),decimalScale=i16(bytes,s5.start+17),bits=bytes[s5.start+19],bitmapIndicator=s6?bytes[s6.start+5]:255;if(bitmapIndicator!==255&&bitmapIndicator!==0)throw new Error("Unsupported bitmap");if(bits===0)return reference*Math.pow(10,-decimalScale);const packed=bytes.subarray(s7.start+5,s7.start+s7.length),x=readBits(packed,0,bits);return(reference+x*Math.pow(2,binaryScale))*Math.pow(10,-decimalScale)}
function noaaFilterUrl(cycle,forecastHour,varName,lat,lon){const fh=pad(forecastHour,3),file=`gfswave.t${cycle.hour}z.global.0p25.f${fh}.grib2`,d=.13,p=new URLSearchParams();p.set("file",file);p.set(`var_${varName}`,"on");p.set("lev_surface","on");p.set("subregion","");p.set("leftlon",String(Math.max(-180,lon-d)));p.set("rightlon",String(Math.min(180,lon+d)));p.set("toplat",String(Math.min(90,lat+d)));p.set("bottomlat",String(Math.max(-90,lat-d)));p.set("dir",cycle.dir);return`${NOAA_FILTER}?${p.toString()}`}
async function waveField(cycle,fh,varName,lat,lon){const key=`${cycle.date}${cycle.hour}:${fh}:${varName}:${lat.toFixed(2)}:${lon.toFixed(2)}`,hit=waveCache.get(key);if(hit&&hit.expires>Date.now())return hit.value;try{const r=await timedFetch(noaaFilterUrl(cycle,fh,varName,lat,lon),{headers:{accept:"application/octet-stream"}},3500);if(!r.ok)return null;const b=new Uint8Array(await r.arrayBuffer()),v=decodeSimpleFirst(b);if(!Number.isFinite(v))return null;waveCache.set(key,{value:v,expires:Date.now()+20*60*1000});return v}catch{return null}}
function forecastHour(cycleMs,time){const t=Date.parse(time||"");if(!Number.isFinite(t))return 3;const raw=(t-cycleMs)/3600000;return Math.max(3,Math.min(384,Math.round(raw/3)*3))}
async function noaaForForecast(lat,lon,forecast){const cycle=await latestCycle();if(!cycle)return{ok:false,status:"no-cycle",byHour:new Map(),count:0};const hours=[...new Set(forecast.map(r=>forecastHour(cycle.ms,r.forecastTime)))];const byHour=new Map();await Promise.all(hours.map(async fh=>{const[hs,period,direction]=await Promise.all([waveField(cycle,fh,"HTSGW",lat,lon),waveField(cycle,fh,"PERPW",lat,lon),waveField(cycle,fh,"DIRPW",lat,lon)]);if(hs!=null)byHour.set(fh,{hs,wavePeriod:period,waveDirection:direction})}));return{ok:byHour.size>0,status:byHour.size?"ok":"no-data",byHour,count:byHour.size,cycle}}

async function pointWeather(url){const lat=num(url.searchParams.get("lat")),lon=num(url.searchParams.get("lon")),limit=Math.max(1,Math.min(24,Number(url.searchParams.get("limit"))||12));if(lat==null||lon==null||lat<-90||lat>90||lon<-180||lon>180)return json({error:"Invalid latitude/longitude"},400);const key=`${lat.toFixed(4)}:${lon.toFixed(4)}:${limit}`,hit=weatherCache.get(key);if(hit&&hit.expires>Date.now())return json(hit.data);const q=`lat=${encodeURIComponent(lat.toFixed(4))}&lon=${encodeURIComponent(lon.toFixed(4))}`;
  const locationPromise=fetchMet(`${MET_LOCATION_URL}?${q}`,3500),oceanPromise=fetchMet(`${MET_OCEAN_URL}?${q}`,3500);const location=await locationPromise,locationRows=location.ok?rows(location.data):[];if(!locationRows.length)return json({error:"Weather forecast unavailable",diagnostics:{location:{ok:false,status:location.status,error:location.error||null}}},502);
  const altitudeM=geometry(location.data)?.alt??null;base:0;
  if(altitudeM!=null&&altitudeM>10){const data={lat,lon,forecast:inlandForecast(locationRows,limit),sources:{weather:"MET Norway Locationforecast",marine:null},marineFallback:false,marineSuppressed:true,diagnostics:{location:{ok:true,status:"ok",count:locationRows.length,altitudeM},ocean:{ok:false,status:"skipped-land",count:0,error:null,snapNm:null,suppressed:true},globalWave:{ok:false,status:"land-suppressed",count:0}}};weatherCache.set(key,{data,expires:Date.now()+10*60*1000});return json(data)}
  const ocean=await oceanPromise,oceanRows=ocean.ok?rows(ocean.data):[],requested={lat,lon},oceanPoint=geometry(ocean.data),snapNm=distanceNm(requested,oceanPoint),landLikely=(altitudeM!=null&&altitudeM>0&&snapNm!=null&&snapNm>1.5),oceanUsable=!landLikely&&oceanRows.length>0&&(snapNm==null||snapNm<=3),base=selectFuture(locationRows,limit);let forecast=base.map(l=>combined(l,oceanUsable?nearest(oceanRows,l.time):null)),marineSource=oceanUsable&&forecast.some(x=>x.hs!=null)?"MET Norway Oceanforecast":null,globalWave={ok:false,status:landLikely?"land-suppressed":"not-needed",count:0};
  if(!landLikely&&!forecast.some(x=>x.hs!=null)){try{globalWave=await Promise.race([noaaForForecast(lat,lon,forecast),new Promise(resolve=>setTimeout(()=>resolve({ok:false,status:"timeout",count:0,byHour:new Map()}),3800))]);if(globalWave.ok){forecast=forecast.map(r=>{const w=globalWave.byHour.get(forecastHour(globalWave.cycle.ms,r.forecastTime));return w?{...r,...w}:r});marineSource="NOAA/NCEP GFS-Wave"}}catch{globalWave={ok:false,status:"error",count:0}}}
  forecast=forecast.map(r=>{const x={...r};delete x.currentKn;delete x.currentDirection;return x});if(landLikely)forecast=forecast.map(r=>({...r,hs:null,waveDirection:null,wavePeriod:null,seaTemp:null}));const data={lat,lon,forecast,sources:{weather:"MET Norway Locationforecast",marine:landLikely?null:marineSource},marineFallback:marineSource==="NOAA/NCEP GFS-Wave",marineSuppressed:landLikely,diagnostics:{location:{ok:true,status:"ok",count:locationRows.length,altitudeM},ocean:{ok:ocean.ok,status:ocean.ok?"ok":ocean.status,count:oceanRows.length,error:ocean.error||null,snapNm:snapNm==null?null:Number(snapNm.toFixed(2)),suppressed:landLikely||!oceanUsable},globalWave:{ok:Boolean(globalWave.ok),status:globalWave.status,count:globalWave.count||0,provider:"NOAA/NCEP GFS-Wave"}}};weatherCache.set(key,{data,expires:Date.now()+10*60*1000});return json(data)}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(url.pathname==="/api/weather"&&request.method==="GET")return pointWeather(url);return previousWorker.fetch(request,env,ctx)}};
