import baseWorker from "./worker.js";

const MET_LOCATION_URL="https://api.met.no/weatherapi/locationforecast/2.0/compact";
const MET_OCEAN_URL="https://api.met.no/weatherapi/oceanforecast/2.0/complete";
const NOAA_ROOT="https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod";
const NOAA_FILTER="https://nomads.ncep.noaa.gov/cgi-bin/filter_gfswave.pl";
const PELYR_API_ROOT="https://api.pelyr.com";
const USER_AGENT="MarineTools/8.5.5 contact@marinetools.app";
const PRODUCT_ORIGINS=new Set(["https://marinetools.app","https://www.marinetools.app"]);
const cors={"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type"};

const weatherCache=new Map(),cycleCache={value:null,expires:0},waveCache=new Map(),pelyrAisCache=new Map();
let pelyrSourcesCache={expires:0,map:null};

function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...cors,"content-type":"application/json;charset=utf-8","cache-control":"no-store",...extra}})}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function msToKn(v){return v==null?null:v*1.943844}
function rad(x){return x*Math.PI/180}
function pad(n,w=2){return String(n).padStart(w,"0")}
function uniq(values){return [...new Set(values.filter(Boolean))]}
function rows(d){return Array.isArray(d?.properties?.timeseries)?d.properties.timeseries:[]}
function geometry(d){const c=d?.geometry?.coordinates;if(!Array.isArray(c)||c.length<2)return null;const lon=num(c[0]),lat=num(c[1]),alt=num(c[2]);return lon==null||lat==null?null:{lat,lon,alt}}
function detail(row,key){return num(row?.data?.instant?.details?.[key])}
function periodDetail(row,key){for(const p of ["next_1_hours","next_6_hours","next_12_hours"]){const v=num(row?.data?.[p]?.details?.[key]);if(v!=null)return v}return null}
function periodSummary(row,key){for(const p of ["next_1_hours","next_6_hours","next_12_hours"]){const v=row?.data?.[p]?.summary?.[key];if(v!=null)return v}return null}
function selectFuture(series,limit){const now=Date.now()-45*60*1000,f=series.filter(r=>{const t=Date.parse(r?.time||"");return Number.isFinite(t)&&t>=now});return(f.length?f:series).slice(0,limit)}
function nearest(series,time,maxMs=90*60*1000){if(!series?.length)return null;const target=Date.parse(time||"");if(!Number.isFinite(target))return series[0]||null;let best=null,d=Infinity;for(const row of series){const t=Date.parse(row?.time||row?.forecastTime||"");if(!Number.isFinite(t))continue;const q=Math.abs(t-target);if(q<d){d=q;best=row}}return d<=maxMs?best:null}
function distanceNm(a,b){if(!a||!b)return null;const R=3440.065,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function combined(locationRow,oceanRow){return{forecastTime:locationRow?.time||oceanRow?.time||null,hs:detail(oceanRow,"sea_surface_wave_height"),waveDirection:detail(oceanRow,"sea_surface_wave_from_direction"),wavePeriod:detail(oceanRow,"sea_surface_wave_period_at_variance_spectral_density_maximum"),windKn:msToKn(detail(locationRow,"wind_speed")),windDirection:detail(locationRow,"wind_from_direction"),airTemp:detail(locationRow,"air_temperature"),seaTemp:detail(oceanRow,"sea_water_temperature"),precipitation:periodDetail(locationRow,"precipitation_amount"),symbolCode:periodSummary(locationRow,"symbol_code"),source:"MET Norway"}}

async function timedFetch(url,init={},timeoutMs=4500){const ac=new AbortController(),timer=setTimeout(()=>ac.abort("timeout"),timeoutMs);try{return await fetch(url,{...init,signal:ac.signal,headers:{"user-agent":USER_AGENT,...(init.headers||{})}})}finally{clearTimeout(timer)}}
async function fetchMet(url,timeoutMs=3500){try{const r=await timedFetch(url,{headers:{accept:"application/json"}},timeoutMs),text=await r.text();let data=null;try{data=JSON.parse(text)}catch{}return r.ok?{ok:true,status:r.status,data}:{ok:false,status:r.status,error:(data?.error||text||"").slice(0,240),data}}catch(err){return{ok:false,status:"timeout",error:String(err?.message||err),data:null}}}
function inlandForecast(locationRows,limit){return selectFuture(locationRows,limit).map(r=>combined(r,null)).map(r=>({...r,hs:null,waveDirection:null,wavePeriod:null,seaTemp:null}))}

function cycleCandidates(now=new Date()){const t=new Date(now);t.setUTCMinutes(0,0,0);t.setUTCHours(Math.floor(t.getUTCHours()/6)*6);const out=[];for(let i=0;i<5;i++){const d=new Date(t.getTime()-i*6*3600000);out.push({date:`${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}`,hour:pad(d.getUTCHours()),ms:Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours())})}return out}
async function latestCycle(){if(cycleCache.value&&cycleCache.expires>Date.now())return cycleCache.value;for(const c of cycleCandidates()){const file=`gfswave.t${c.hour}z.global.0p25.f003.grib2`,dir=`/gfs.${c.date}/${c.hour}/wave/gridded`,base=`${NOAA_ROOT}${dir}/${file}`;try{const r=await timedFetch(`${base}.idx`,{headers:{accept:"text/plain"}},2500);if(r.ok){const text=await r.text();if(/:HTSGW:/.test(text)){const v={...c,dir};cycleCache.value=v;cycleCache.expires=Date.now()+15*60*1000;return v}}}catch{}}return null}
function u32(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(o,false)}
function i16(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getInt16(o,false)}
function f32(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getFloat32(o,false)}
function gribSections(bytes){if(bytes.length<20||String.fromCharCode(...bytes.slice(0,4))!=="GRIB")throw new Error("Not GRIB2");const out={};let p=16;while(p+5<=bytes.length){if(String.fromCharCode(...bytes.slice(p,p+4))==="7777")break;const len=u32(bytes,p),no=bytes[p+4];if(!(len>=5)||p+len>bytes.length)throw new Error("Invalid GRIB2 section");out[no]={start:p,length:len};p+=len}return out}
function readBits(bytes,bitOffset,width){let v=0;for(let i=0;i<width;i++){const q=bitOffset+i,byte=bytes[q>>3],bit=7-(q&7);v=v*2+((byte>>bit)&1)}return v}
function decodeSimpleFirst(bytes){const s=gribSections(bytes),s5=s[5],s6=s[6],s7=s[7];if(!s5||!s7)throw new Error("Missing GRIB2 data");const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),template=dv.getUint16(s5.start+9,false);if(template!==0)throw new Error(`Unsupported packing ${template}`);const reference=f32(bytes,s5.start+11),binaryScale=i16(bytes,s5.start+15),decimalScale=i16(bytes,s5.start+17),bits=bytes[s5.start+19],bitmapIndicator=s6?bytes[s6.start+5]:255;if(bitmapIndicator!==255&&bitmapIndicator!==0)throw new Error("Unsupported bitmap");if(bits===0)return reference*Math.pow(10,-decimalScale);const packed=bytes.subarray(s7.start+5,s7.start+s7.length),x=readBits(packed,0,bits);return(reference+x*Math.pow(2,binaryScale))*Math.pow(10,-decimalScale)}
function noaaFilterUrl(cycle,forecastHour,varName,lat,lon){const fh=pad(forecastHour,3),file=`gfswave.t${cycle.hour}z.global.0p25.f${fh}.grib2`,d=.13,p=new URLSearchParams();p.set("file",file);p.set(`var_${varName}`,"on");p.set("lev_surface","on");p.set("subregion","");p.set("leftlon",String(Math.max(-180,lon-d)));p.set("rightlon",String(Math.min(180,lon+d)));p.set("toplat",String(Math.min(90,lat+d)));p.set("bottomlat",String(Math.max(-90,lat-d)));p.set("dir",cycle.dir);return`${NOAA_FILTER}?${p.toString()}`}
async function waveField(cycle,fh,varName,lat,lon){const key=`${cycle.date}${cycle.hour}:${fh}:${varName}:${lat.toFixed(2)}:${lon.toFixed(2)}`,hit=waveCache.get(key);if(hit&&hit.expires>Date.now())return hit.value;try{const r=await timedFetch(noaaFilterUrl(cycle,fh,varName,lat,lon),{headers:{accept:"application/octet-stream"}},3500);if(!r.ok)return null;const b=new Uint8Array(await r.arrayBuffer()),v=decodeSimpleFirst(b);if(!Number.isFinite(v))return null;waveCache.set(key,{value:v,expires:Date.now()+20*60*1000});return v}catch{return null}}
function forecastHour(cycleMs,time){const t=Date.parse(time||"");if(!Number.isFinite(t))return 3;const raw=(t-cycleMs)/3600000;return Math.max(3,Math.min(384,Math.round(raw/3)*3))}
async function waveForPoint(cycle,lat,lon,time){const fh=forecastHour(cycle.ms,time);const[hs,period,direction]=await Promise.all([waveField(cycle,fh,"HTSGW",lat,lon),waveField(cycle,fh,"PERPW",lat,lon),waveField(cycle,fh,"DIRPW",lat,lon)]);return hs==null?null:{hs,wavePeriod:period,waveDirection:direction,marineSource:"NOAA/NCEP GFS-Wave"}}
async function noaaForForecast(lat,lon,forecast){const cycle=await latestCycle();if(!cycle)return{ok:false,status:"no-cycle",byHour:new Map(),count:0};const hours=[...new Set(forecast.map(r=>forecastHour(cycle.ms,r.forecastTime)))],byHour=new Map();await Promise.all(hours.map(async fh=>{const[hs,period,direction]=await Promise.all([waveField(cycle,fh,"HTSGW",lat,lon),waveField(cycle,fh,"PERPW",lat,lon),waveField(cycle,fh,"DIRPW",lat,lon)]);if(hs!=null)byHour.set(fh,{hs,wavePeriod:period,waveDirection:direction})}));return{ok:byHour.size>0,status:byHour.size?"ok":"no-data",byHour,count:byHour.size,cycle}}

async function pointWeather(url){const lat=num(url.searchParams.get("lat")),lon=num(url.searchParams.get("lon")),limit=Math.max(1,Math.min(24,Number(url.searchParams.get("limit"))||12));if(lat==null||lon==null||lat<-90||lat>90||lon<-180||lon>180)return json({error:"Invalid latitude/longitude"},400);const key=`${lat.toFixed(4)}:${lon.toFixed(4)}:${limit}`,hit=weatherCache.get(key);if(hit&&hit.expires>Date.now())return json(hit.data);const q=`lat=${encodeURIComponent(lat.toFixed(4))}&lon=${encodeURIComponent(lon.toFixed(4))}`;
  const locationPromise=fetchMet(`${MET_LOCATION_URL}?${q}`,3500),oceanPromise=fetchMet(`${MET_OCEAN_URL}?${q}`,3500);const location=await locationPromise,locationRows=location.ok?rows(location.data):[];if(!locationRows.length)return json({error:"Weather forecast unavailable",diagnostics:{location:{ok:false,status:location.status,error:location.error||null}}},502);
  const altitudeM=geometry(location.data)?.alt??null;
  if(altitudeM!=null&&altitudeM>10){const data={lat,lon,forecast:inlandForecast(locationRows,limit),sources:{weather:"MET Norway Locationforecast",marine:null},marineFallback:false,marineSuppressed:true,diagnostics:{location:{ok:true,status:"ok",count:locationRows.length,altitudeM},ocean:{ok:false,status:"skipped-land",count:0,error:null,snapNm:null,suppressed:true},globalWave:{ok:false,status:"land-suppressed",count:0}}};weatherCache.set(key,{data,expires:Date.now()+10*60*1000});return json(data)}
  const ocean=await oceanPromise,oceanRows=ocean.ok?rows(ocean.data):[],requested={lat,lon},oceanPoint=geometry(ocean.data),snapNm=distanceNm(requested,oceanPoint),landLikely=(altitudeM!=null&&altitudeM>0&&snapNm!=null&&snapNm>1.5),oceanUsable=!landLikely&&oceanRows.length>0&&(snapNm==null||snapNm<=3),base=selectFuture(locationRows,limit);let forecast=base.map(l=>combined(l,oceanUsable?nearest(oceanRows,l.time):null)),marineSource=oceanUsable&&forecast.some(x=>x.hs!=null)?"MET Norway Oceanforecast":null,globalWave={ok:false,status:landLikely?"land-suppressed":"not-needed",count:0};
  if(!landLikely&&!forecast.some(x=>x.hs!=null)){try{globalWave=await Promise.race([noaaForForecast(lat,lon,forecast),new Promise(resolve=>setTimeout(()=>resolve({ok:false,status:"timeout",count:0,byHour:new Map()}),3800))]);if(globalWave.ok){forecast=forecast.map(r=>{const w=globalWave.byHour.get(forecastHour(globalWave.cycle.ms,r.forecastTime));return w?{...r,...w}:r});marineSource="NOAA/NCEP GFS-Wave"}}catch{globalWave={ok:false,status:"error",count:0}}}
  forecast=forecast.map(r=>{const x={...r};delete x.currentKn;delete x.currentDirection;return x});if(landLikely)forecast=forecast.map(r=>({...r,hs:null,waveDirection:null,wavePeriod:null,seaTemp:null}));const data={lat,lon,forecast,sources:{weather:"MET Norway Locationforecast",marine:landLikely?null:marineSource},marineFallback:marineSource==="NOAA/NCEP GFS-Wave",marineSuppressed:landLikely,diagnostics:{location:{ok:true,status:"ok",count:locationRows.length,altitudeM},ocean:{ok:ocean.ok,status:ocean.ok?"ok":ocean.status,count:oceanRows.length,error:ocean.error||null,snapNm:snapNm==null?null:Number(snapNm.toFixed(2)),suppressed:landLikely||!oceanUsable},globalWave:{ok:Boolean(globalWave.ok),status:globalWave.status,count:globalWave.count||0,provider:"NOAA/NCEP GFS-Wave"}}};weatherCache.set(key,{data,expires:Date.now()+10*60*1000});return json(data)}

function parseBounds(url){const b={minLat:num(url.searchParams.get("minLat")),maxLat:num(url.searchParams.get("maxLat")),minLon:num(url.searchParams.get("minLon")),maxLon:num(url.searchParams.get("maxLon"))};if(Object.values(b).some(v=>v==null))return null;if(b.minLat<-90||b.maxLat>90||b.minLon<-180||b.maxLon>180||b.minLat>=b.maxLat||b.minLon>=b.maxLon)return null;return b}
function intersectsBarentsWatchArea(b){return Boolean(b&&b.maxLat>=53&&b.minLat<=84&&b.maxLon>=-35&&b.minLon<=45)}
function productOriginAllowed(request){return PRODUCT_ORIGINS.has(request.headers.get("origin")||"")}
async function pelyrSources(env){if(!env.PELYR_API_KEY)throw new Error("Pelyr API key is not configured");if(pelyrSourcesCache.map&&pelyrSourcesCache.expires>Date.now())return pelyrSourcesCache.map;const r=await timedFetch(`${PELYR_API_ROOT}/v1/sources`,{headers:{authorization:`Bearer ${env.PELYR_API_KEY}`,accept:"application/json"}},3500);if(!r.ok)throw new Error(`Pelyr sources request failed (${r.status})`);const j=await r.json(),map=new Map((Array.isArray(j?.sources)?j.sources:[]).map(s=>[String(s.id),s]));pelyrSourcesCache={map,expires:Date.now()+30*60*1000};return map}
function pelyrCacheKey(b){return[b.minLat,b.maxLat,b.minLon,b.maxLon].map(v=>Number(v).toFixed(2)).join(":")}
async function pelyrLatest(url,env){const b=parseBounds(url);if(!b)throw new Error("Invalid AIS bounding box");const key=pelyrCacheKey(b),hit=pelyrAisCache.get(key);if(hit&&hit.expires>Date.now())return hit.data;const sourceMap=await pelyrSources(env),bbox=[b.minLon,b.minLat,b.maxLon,b.maxLat].join(","),endpoint=`${PELYR_API_ROOT}/v1/vessels?bbox=${encodeURIComponent(bbox)}&max=2000`,r=await timedFetch(endpoint,{headers:{authorization:`Bearer ${env.PELYR_API_KEY}`,accept:"application/json"}},4500);if(!r.ok)throw new Error(`Pelyr AIS request failed (${r.status})`);const j=await r.json(),vessels=[];for(const vessel of Array.isArray(j?.vessels)?j.vessels:[]){const p=vessel?.position;if(!p)continue;const lat=num(p.lat),lon=num(p.lon);if(lat==null||lon==null)continue;const pSource=sourceMap.get(String(p.license??"")),openLicence=x=>Boolean(x&&(/NLOD/i.test(String(x.license||""))||/CC[-_ ]?BY/i.test(String(x.license||""))));if(!openLicence(pSource))continue;const s=vessel?.static||null,sSource=s?sourceMap.get(String(s.license??"")):null,staticAllowed=!s||openLicence(sSource),attrs=uniq([pSource?.attribution,staticAllowed?sSource?.attribution:null]);vessels.push({mmsi:vessel.mmsi,name:staticAllowed?(s?.name||null):null,shipName:staticAllowed?(s?.name||null):null,latitude:lat,longitude:lon,speedOverGround:num(p.sog),courseOverGround:num(p.cog),trueHeading:num(p.heading),navigationalStatus:num(p.nav_status),shipType:staticAllowed?num(s?.type):null,timestamp:p.ts||null,source:pSource?.source||"Open AIS source",attributions:attrs,dataAgeSource:p.ts||null})}const data={vessels,generatedAt:j?.generated_at||new Date().toISOString(),truncated:Boolean(j?.truncated)};pelyrAisCache.set(key,{data,expires:Date.now()+15*1000});return data}
async function barentsWatchAis(request,env,ctx){const base=await baseWorker.fetch(request,env,ctx);if(!base.ok)return null;try{const arr=await base.clone().json();if(!Array.isArray(arr))return null;return arr.map(v=>({...v,source:v?.source||"BarentsWatch",attributions:uniq([...(Array.isArray(v?.attributions)?v.attributions:[]),"Data delivered by BarentsWatch"])}))}catch{return null}}
async function aisResponse(request,env,ctx){const url=new URL(request.url),bounds=parseBounds(url);if(!productOriginAllowed(request))return json({error:"AIS context is available only inside the Marine Tools web application."},403,{"access-control-allow-origin":"null"});const bwArea=intersectsBarentsWatchArea(bounds);if(bwArea){try{const bw=await barentsWatchAis(request,env,ctx);if(Array.isArray(bw)&&bw.length)return json(bw,200,{"access-control-allow-origin":request.headers.get("origin"),"vary":"Origin","x-marine-tools-ais-provider":"BarentsWatch"})}catch{}}
  if(env.PELYR_API_KEY){try{const p=await pelyrLatest(url,env);if(p.vessels.length||!bwArea)return json(p.vessels,200,{"access-control-allow-origin":request.headers.get("origin"),"vary":"Origin","x-marine-tools-ais-provider":"Pelyr-open-sources"})}catch{}}
  if(!bwArea){try{const bw=await barentsWatchAis(request,env,ctx);if(Array.isArray(bw)&&bw.length)return json(bw,200,{"access-control-allow-origin":request.headers.get("origin"),"vary":"Origin","x-marine-tools-ais-provider":"BarentsWatch"})}catch{}}
  return json([],200,{"access-control-allow-origin":request.headers.get("origin"),"vary":"Origin","x-marine-tools-ais-provider":"none"})}

async function routeForecastResponse(request,env,ctx){const base=await baseWorker.fetch(request,env,ctx);if(!base.ok)return base;let data;try{data=await base.clone().json()}catch{return base}if(!Array.isArray(data))return base;const cycle=await Promise.race([latestCycle(),new Promise(resolve=>setTimeout(()=>resolve(null),2200))]);if(!cycle)return json(data);const out=await Promise.all(data.map(async row=>{if(row?.hs!=null)return{...row,marineSource:"MET Norway Oceanforecast"};const lat=num(row?.lat),lon=num(row?.lon);if(lat==null||lon==null)return row;const wave=await Promise.race([waveForPoint(cycle,lat,lon,row?.forecastTime),new Promise(resolve=>setTimeout(()=>resolve(null),3200))]);return wave?{...row,...wave}:row}));return json(out)}
async function healthResponse(request,env,ctx){const base=await baseWorker.fetch(request,env,ctx);if(!base.ok)return base;let j;try{j=await base.clone().json()}catch{return base}const capabilities=Array.isArray(j?.capabilities)?[...j.capabilities]:[];for(const cap of ["global-wave-fallback","global-open-ais"]){if(!capabilities.includes(cap))capabilities.push(cap)}return json({...j,capabilities,globalWaveConfigured:true,globalWaveProvider:"NOAA/NCEP GFS-Wave",globalAisConfigured:Boolean(env.PELYR_API_KEY),globalAisProvider:env.PELYR_API_KEY?"BarentsWatch in supported region; open-license Pelyr sources elsewhere/fallback":"BarentsWatch only"})}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="OPTIONS"&&url.pathname==="/api/ais/latest"){const origin=request.headers.get("origin")||"";if(!PRODUCT_ORIGINS.has(origin))return new Response(null,{status:403});return new Response(null,{status:204,headers:{"access-control-allow-origin":origin,"access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type","vary":"Origin"}})}if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(url.pathname==="/api/ais/latest")return aisResponse(request,env,ctx);if(url.pathname==="/api/weather"&&request.method==="GET")return pointWeather(url);if(url.pathname==="/api/forecast"&&request.method==="GET")return routeForecastResponse(request,env,ctx);if(url.pathname==="/api/health")return healthResponse(request,env,ctx);return baseWorker.fetch(request,env,ctx)}};
